# templates
variables:
  UV_CACHE_DIR: "$CI_PROJECT_DIR/.cache/uv"

.test_template: &test
  stage: test
  image: ghcr.io/astral-sh/uv:python3.13-trixie-slim
  cache:
    key:
      files:
        - uv.lock
    paths:
      - .cache/uv
  before_script:
    - uv sync --locked
  rules:
    - if: $CI_COMMIT_BRANCH

.build_template:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "$CI_COMMIT_SHA" > COMMIT_HASH
    - >
      echo "{
        \"auths\": {
          \"$CI_REGISTRY\": {
            \"username\": \"$CI_REGISTRY_USER\",
            \"password\":\"$CI_REGISTRY_PASSWORD\"
          }
        }
      }" > /kaniko/.docker/config.json
    - >
      /kaniko/executor --context $CI_PROJECT_DIR \
        --dockerfile $CI_PROJECT_DIR/Dockerfile \
        --destination $CI_REGISTRY_IMAGE:$TARGET_REF \
        --cache=true \
        --cache-ttl=120h

stages:
  - build
  - test

build_branches:
  extends: .build_template
  variables:
    TARGET_REF: $CI_COMMIT_BRANCH
  only:
    - branches

build_tags:
  extends: .build_template
  variables:
    TARGET_REF: $CI_COMMIT_TAG
  only:
    - tags

test_ruff:
  <<: *test
  script:
    - uv run ruff check .
    - uv run ruff format --check
